language: java
jdk:
  - openjdk8

branches:
  only:
    - master


# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r neighborhoodclub-api *
  - mkdir -p deploy
  - mv neighborhoodclub-api.zip deploy/neighborhoodclub-api.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: neighborhoodclub-api-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: neighborhoodclub-api-build
      key: neighborhoodclub-api.zip
      bundle_type: zip
      application: neighborhoodclub-api
      deployment_group: neighborhoodclub-api-group
      region: ap-northeast-2
      wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wngh7247@gmail.com